repos:
-   repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
    -   id: poetry-check
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.4
  hooks:
    - id: ruff
      args: [--extend-ignore, D1]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        additional_dependencies: [
          django-stubs>=4.2,
          django-environ>=0.11,
          django-admin-rangefilter>=0.11,
          tldextract>=5.0,
          confusable_homoglyphs>=3.2,
          types-requests>=2.31,
          django_extensions>=3.2,
          django-allauth>=0.58
        ]