# Generated by Django 4.2.7 on 2023-11-04 22:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dangerdine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessratinglocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=[], srid=4326, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
