# Generated by Django 4.2.7 on 2023-11-04 22:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangerdine', '0002_remove_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRatingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^(?![\\s'-])(?!.*[\\s'-]{2})[A-Za-z '-]+(?<![\\s'-])\\Z"), django.core.validators.MinLengthValidator(2)], verbose_name='Name')),
                ('food_hygiene_rating', models.PositiveIntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Food Hygiene Rating')),
            ],
            options={
                'verbose_name': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='LocationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_rating_locations', models.ManyToManyField(help_text='The set of business rating locations in this route.', related_name='location_routes', to='dangerdine.businessratinglocation', verbose_name='Business Rating Locations')),
                ('user', models.ForeignKey(help_text='The user that owns this route.', on_delete=django.db.models.deletion.CASCADE, related_name='location_routes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Location Route',
            },
        ),
    ]
