# Generated by Django 4.2.7 on 2023-11-05 10:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dangerdine', '0007_alter_businessratinglocation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationroute',
            name='anchor',
            field=django.contrib.gis.db.models.fields.PointField(default=[], srid=4326, verbose_name='Anchor Location'),
            preserve_default=False,
        ),
    ]
